/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: protocol.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "protocol.pb-c.h"
void   pb__pub_msg__init
                     (Pb__PubMsg         *message)
{
  static const Pb__PubMsg init_value = PB__PUB_MSG__INIT;
  *message = init_value;
}
size_t pb__pub_msg__get_packed_size
                     (const Pb__PubMsg *message)
{
  assert(message->base.descriptor == &pb__pub_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pb__pub_msg__pack
                     (const Pb__PubMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pb__pub_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pb__pub_msg__pack_to_buffer
                     (const Pb__PubMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pb__pub_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Pb__PubMsg *
       pb__pub_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Pb__PubMsg *)
     protobuf_c_message_unpack (&pb__pub_msg__descriptor,
                                allocator, len, data);
}
void   pb__pub_msg__free_unpacked
                     (Pb__PubMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &pb__pub_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   pb__pub_ack__init
                     (Pb__PubAck         *message)
{
  static const Pb__PubAck init_value = PB__PUB_ACK__INIT;
  *message = init_value;
}
size_t pb__pub_ack__get_packed_size
                     (const Pb__PubAck *message)
{
  assert(message->base.descriptor == &pb__pub_ack__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pb__pub_ack__pack
                     (const Pb__PubAck *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pb__pub_ack__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pb__pub_ack__pack_to_buffer
                     (const Pb__PubAck *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pb__pub_ack__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Pb__PubAck *
       pb__pub_ack__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Pb__PubAck *)
     protobuf_c_message_unpack (&pb__pub_ack__descriptor,
                                allocator, len, data);
}
void   pb__pub_ack__free_unpacked
                     (Pb__PubAck *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &pb__pub_ack__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   pb__msg_proto__init
                     (Pb__MsgProto         *message)
{
  static const Pb__MsgProto init_value = PB__MSG_PROTO__INIT;
  *message = init_value;
}
size_t pb__msg_proto__get_packed_size
                     (const Pb__MsgProto *message)
{
  assert(message->base.descriptor == &pb__msg_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pb__msg_proto__pack
                     (const Pb__MsgProto *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pb__msg_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pb__msg_proto__pack_to_buffer
                     (const Pb__MsgProto *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pb__msg_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Pb__MsgProto *
       pb__msg_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Pb__MsgProto *)
     protobuf_c_message_unpack (&pb__msg_proto__descriptor,
                                allocator, len, data);
}
void   pb__msg_proto__free_unpacked
                     (Pb__MsgProto *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &pb__msg_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   pb__ack__init
                     (Pb__Ack         *message)
{
  static const Pb__Ack init_value = PB__ACK__INIT;
  *message = init_value;
}
size_t pb__ack__get_packed_size
                     (const Pb__Ack *message)
{
  assert(message->base.descriptor == &pb__ack__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pb__ack__pack
                     (const Pb__Ack *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pb__ack__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pb__ack__pack_to_buffer
                     (const Pb__Ack *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pb__ack__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Pb__Ack *
       pb__ack__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Pb__Ack *)
     protobuf_c_message_unpack (&pb__ack__descriptor,
                                allocator, len, data);
}
void   pb__ack__free_unpacked
                     (Pb__Ack *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &pb__ack__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   pb__connect_request__init
                     (Pb__ConnectRequest         *message)
{
  static const Pb__ConnectRequest init_value = PB__CONNECT_REQUEST__INIT;
  *message = init_value;
}
size_t pb__connect_request__get_packed_size
                     (const Pb__ConnectRequest *message)
{
  assert(message->base.descriptor == &pb__connect_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pb__connect_request__pack
                     (const Pb__ConnectRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pb__connect_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pb__connect_request__pack_to_buffer
                     (const Pb__ConnectRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pb__connect_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Pb__ConnectRequest *
       pb__connect_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Pb__ConnectRequest *)
     protobuf_c_message_unpack (&pb__connect_request__descriptor,
                                allocator, len, data);
}
void   pb__connect_request__free_unpacked
                     (Pb__ConnectRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &pb__connect_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   pb__connect_response__init
                     (Pb__ConnectResponse         *message)
{
  static const Pb__ConnectResponse init_value = PB__CONNECT_RESPONSE__INIT;
  *message = init_value;
}
size_t pb__connect_response__get_packed_size
                     (const Pb__ConnectResponse *message)
{
  assert(message->base.descriptor == &pb__connect_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pb__connect_response__pack
                     (const Pb__ConnectResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pb__connect_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pb__connect_response__pack_to_buffer
                     (const Pb__ConnectResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pb__connect_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Pb__ConnectResponse *
       pb__connect_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Pb__ConnectResponse *)
     protobuf_c_message_unpack (&pb__connect_response__descriptor,
                                allocator, len, data);
}
void   pb__connect_response__free_unpacked
                     (Pb__ConnectResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &pb__connect_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   pb__ping__init
                     (Pb__Ping         *message)
{
  static const Pb__Ping init_value = PB__PING__INIT;
  *message = init_value;
}
size_t pb__ping__get_packed_size
                     (const Pb__Ping *message)
{
  assert(message->base.descriptor == &pb__ping__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pb__ping__pack
                     (const Pb__Ping *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pb__ping__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pb__ping__pack_to_buffer
                     (const Pb__Ping *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pb__ping__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Pb__Ping *
       pb__ping__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Pb__Ping *)
     protobuf_c_message_unpack (&pb__ping__descriptor,
                                allocator, len, data);
}
void   pb__ping__free_unpacked
                     (Pb__Ping *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &pb__ping__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   pb__ping_response__init
                     (Pb__PingResponse         *message)
{
  static const Pb__PingResponse init_value = PB__PING_RESPONSE__INIT;
  *message = init_value;
}
size_t pb__ping_response__get_packed_size
                     (const Pb__PingResponse *message)
{
  assert(message->base.descriptor == &pb__ping_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pb__ping_response__pack
                     (const Pb__PingResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pb__ping_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pb__ping_response__pack_to_buffer
                     (const Pb__PingResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pb__ping_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Pb__PingResponse *
       pb__ping_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Pb__PingResponse *)
     protobuf_c_message_unpack (&pb__ping_response__descriptor,
                                allocator, len, data);
}
void   pb__ping_response__free_unpacked
                     (Pb__PingResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &pb__ping_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   pb__subscription_request__init
                     (Pb__SubscriptionRequest         *message)
{
  static const Pb__SubscriptionRequest init_value = PB__SUBSCRIPTION_REQUEST__INIT;
  *message = init_value;
}
size_t pb__subscription_request__get_packed_size
                     (const Pb__SubscriptionRequest *message)
{
  assert(message->base.descriptor == &pb__subscription_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pb__subscription_request__pack
                     (const Pb__SubscriptionRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pb__subscription_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pb__subscription_request__pack_to_buffer
                     (const Pb__SubscriptionRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pb__subscription_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Pb__SubscriptionRequest *
       pb__subscription_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Pb__SubscriptionRequest *)
     protobuf_c_message_unpack (&pb__subscription_request__descriptor,
                                allocator, len, data);
}
void   pb__subscription_request__free_unpacked
                     (Pb__SubscriptionRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &pb__subscription_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   pb__subscription_response__init
                     (Pb__SubscriptionResponse         *message)
{
  static const Pb__SubscriptionResponse init_value = PB__SUBSCRIPTION_RESPONSE__INIT;
  *message = init_value;
}
size_t pb__subscription_response__get_packed_size
                     (const Pb__SubscriptionResponse *message)
{
  assert(message->base.descriptor == &pb__subscription_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pb__subscription_response__pack
                     (const Pb__SubscriptionResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pb__subscription_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pb__subscription_response__pack_to_buffer
                     (const Pb__SubscriptionResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pb__subscription_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Pb__SubscriptionResponse *
       pb__subscription_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Pb__SubscriptionResponse *)
     protobuf_c_message_unpack (&pb__subscription_response__descriptor,
                                allocator, len, data);
}
void   pb__subscription_response__free_unpacked
                     (Pb__SubscriptionResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &pb__subscription_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   pb__unsubscribe_request__init
                     (Pb__UnsubscribeRequest         *message)
{
  static const Pb__UnsubscribeRequest init_value = PB__UNSUBSCRIBE_REQUEST__INIT;
  *message = init_value;
}
size_t pb__unsubscribe_request__get_packed_size
                     (const Pb__UnsubscribeRequest *message)
{
  assert(message->base.descriptor == &pb__unsubscribe_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pb__unsubscribe_request__pack
                     (const Pb__UnsubscribeRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pb__unsubscribe_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pb__unsubscribe_request__pack_to_buffer
                     (const Pb__UnsubscribeRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pb__unsubscribe_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Pb__UnsubscribeRequest *
       pb__unsubscribe_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Pb__UnsubscribeRequest *)
     protobuf_c_message_unpack (&pb__unsubscribe_request__descriptor,
                                allocator, len, data);
}
void   pb__unsubscribe_request__free_unpacked
                     (Pb__UnsubscribeRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &pb__unsubscribe_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   pb__close_request__init
                     (Pb__CloseRequest         *message)
{
  static const Pb__CloseRequest init_value = PB__CLOSE_REQUEST__INIT;
  *message = init_value;
}
size_t pb__close_request__get_packed_size
                     (const Pb__CloseRequest *message)
{
  assert(message->base.descriptor == &pb__close_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pb__close_request__pack
                     (const Pb__CloseRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pb__close_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pb__close_request__pack_to_buffer
                     (const Pb__CloseRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pb__close_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Pb__CloseRequest *
       pb__close_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Pb__CloseRequest *)
     protobuf_c_message_unpack (&pb__close_request__descriptor,
                                allocator, len, data);
}
void   pb__close_request__free_unpacked
                     (Pb__CloseRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &pb__close_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   pb__close_response__init
                     (Pb__CloseResponse         *message)
{
  static const Pb__CloseResponse init_value = PB__CLOSE_RESPONSE__INIT;
  *message = init_value;
}
size_t pb__close_response__get_packed_size
                     (const Pb__CloseResponse *message)
{
  assert(message->base.descriptor == &pb__close_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pb__close_response__pack
                     (const Pb__CloseResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pb__close_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pb__close_response__pack_to_buffer
                     (const Pb__CloseResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pb__close_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Pb__CloseResponse *
       pb__close_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Pb__CloseResponse *)
     protobuf_c_message_unpack (&pb__close_response__descriptor,
                                allocator, len, data);
}
void   pb__close_response__free_unpacked
                     (Pb__CloseResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &pb__close_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor pb__pub_msg__field_descriptors[7] =
{
  {
    "clientID",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Pb__PubMsg, clientid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "guid",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Pb__PubMsg, guid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "subject",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Pb__PubMsg, subject),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "reply",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Pb__PubMsg, reply),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Pb__PubMsg, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "connID",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Pb__PubMsg, connid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sha256",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Pb__PubMsg, sha256),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pb__pub_msg__field_indices_by_name[] = {
  0,   /* field[0] = clientID */
  5,   /* field[5] = connID */
  4,   /* field[4] = data */
  1,   /* field[1] = guid */
  3,   /* field[3] = reply */
  6,   /* field[6] = sha256 */
  2,   /* field[2] = subject */
};
static const ProtobufCIntRange pb__pub_msg__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 10, 6 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor pb__pub_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "pb.PubMsg",
  "PubMsg",
  "Pb__PubMsg",
  "pb",
  sizeof(Pb__PubMsg),
  7,
  pb__pub_msg__field_descriptors,
  pb__pub_msg__field_indices_by_name,
  2,  pb__pub_msg__number_ranges,
  (ProtobufCMessageInit) pb__pub_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor pb__pub_ack__field_descriptors[2] =
{
  {
    "guid",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Pb__PubAck, guid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "error",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Pb__PubAck, error),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pb__pub_ack__field_indices_by_name[] = {
  1,   /* field[1] = error */
  0,   /* field[0] = guid */
};
static const ProtobufCIntRange pb__pub_ack__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor pb__pub_ack__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "pb.PubAck",
  "PubAck",
  "Pb__PubAck",
  "pb",
  sizeof(Pb__PubAck),
  2,
  pb__pub_ack__field_descriptors,
  pb__pub_ack__field_indices_by_name,
  1,  pb__pub_ack__number_ranges,
  (ProtobufCMessageInit) pb__pub_ack__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor pb__msg_proto__field_descriptors[7] =
{
  {
    "sequence",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Pb__MsgProto, sequence),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "subject",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Pb__MsgProto, subject),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "reply",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Pb__MsgProto, reply),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Pb__MsgProto, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timestamp",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Pb__MsgProto, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "redelivered",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Pb__MsgProto, redelivered),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "CRC32",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Pb__MsgProto, crc32),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pb__msg_proto__field_indices_by_name[] = {
  6,   /* field[6] = CRC32 */
  3,   /* field[3] = data */
  5,   /* field[5] = redelivered */
  2,   /* field[2] = reply */
  0,   /* field[0] = sequence */
  1,   /* field[1] = subject */
  4,   /* field[4] = timestamp */
};
static const ProtobufCIntRange pb__msg_proto__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 10, 6 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor pb__msg_proto__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "pb.MsgProto",
  "MsgProto",
  "Pb__MsgProto",
  "pb",
  sizeof(Pb__MsgProto),
  7,
  pb__msg_proto__field_descriptors,
  pb__msg_proto__field_indices_by_name,
  2,  pb__msg_proto__number_ranges,
  (ProtobufCMessageInit) pb__msg_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor pb__ack__field_descriptors[2] =
{
  {
    "subject",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Pb__Ack, subject),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sequence",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Pb__Ack, sequence),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pb__ack__field_indices_by_name[] = {
  1,   /* field[1] = sequence */
  0,   /* field[0] = subject */
};
static const ProtobufCIntRange pb__ack__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor pb__ack__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "pb.Ack",
  "Ack",
  "Pb__Ack",
  "pb",
  sizeof(Pb__Ack),
  2,
  pb__ack__field_descriptors,
  pb__ack__field_indices_by_name,
  1,  pb__ack__number_ranges,
  (ProtobufCMessageInit) pb__ack__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor pb__connect_request__field_descriptors[6] =
{
  {
    "clientID",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Pb__ConnectRequest, clientid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "heartbeatInbox",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Pb__ConnectRequest, heartbeatinbox),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "protocol",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Pb__ConnectRequest, protocol),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "connID",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Pb__ConnectRequest, connid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pingInterval",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Pb__ConnectRequest, pinginterval),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pingMaxOut",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Pb__ConnectRequest, pingmaxout),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pb__connect_request__field_indices_by_name[] = {
  0,   /* field[0] = clientID */
  3,   /* field[3] = connID */
  1,   /* field[1] = heartbeatInbox */
  4,   /* field[4] = pingInterval */
  5,   /* field[5] = pingMaxOut */
  2,   /* field[2] = protocol */
};
static const ProtobufCIntRange pb__connect_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor pb__connect_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "pb.ConnectRequest",
  "ConnectRequest",
  "Pb__ConnectRequest",
  "pb",
  sizeof(Pb__ConnectRequest),
  6,
  pb__connect_request__field_descriptors,
  pb__connect_request__field_indices_by_name,
  1,  pb__connect_request__number_ranges,
  (ProtobufCMessageInit) pb__connect_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor pb__connect_response__field_descriptors[11] =
{
  {
    "pubPrefix",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Pb__ConnectResponse, pubprefix),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "subRequests",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Pb__ConnectResponse, subrequests),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "unsubRequests",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Pb__ConnectResponse, unsubrequests),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "closeRequests",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Pb__ConnectResponse, closerequests),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "error",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Pb__ConnectResponse, error),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "subCloseRequests",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Pb__ConnectResponse, subcloserequests),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pingRequests",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Pb__ConnectResponse, pingrequests),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pingInterval",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Pb__ConnectResponse, pinginterval),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pingMaxOut",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Pb__ConnectResponse, pingmaxout),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "protocol",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Pb__ConnectResponse, protocol),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "publicKey",
    100,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Pb__ConnectResponse, publickey),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pb__connect_response__field_indices_by_name[] = {
  3,   /* field[3] = closeRequests */
  4,   /* field[4] = error */
  7,   /* field[7] = pingInterval */
  8,   /* field[8] = pingMaxOut */
  6,   /* field[6] = pingRequests */
  9,   /* field[9] = protocol */
  0,   /* field[0] = pubPrefix */
  10,   /* field[10] = publicKey */
  5,   /* field[5] = subCloseRequests */
  1,   /* field[1] = subRequests */
  2,   /* field[2] = unsubRequests */
};
static const ProtobufCIntRange pb__connect_response__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 100, 10 },
  { 0, 11 }
};
const ProtobufCMessageDescriptor pb__connect_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "pb.ConnectResponse",
  "ConnectResponse",
  "Pb__ConnectResponse",
  "pb",
  sizeof(Pb__ConnectResponse),
  11,
  pb__connect_response__field_descriptors,
  pb__connect_response__field_indices_by_name,
  2,  pb__connect_response__number_ranges,
  (ProtobufCMessageInit) pb__connect_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor pb__ping__field_descriptors[1] =
{
  {
    "connID",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Pb__Ping, connid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pb__ping__field_indices_by_name[] = {
  0,   /* field[0] = connID */
};
static const ProtobufCIntRange pb__ping__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor pb__ping__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "pb.Ping",
  "Ping",
  "Pb__Ping",
  "pb",
  sizeof(Pb__Ping),
  1,
  pb__ping__field_descriptors,
  pb__ping__field_indices_by_name,
  1,  pb__ping__number_ranges,
  (ProtobufCMessageInit) pb__ping__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor pb__ping_response__field_descriptors[1] =
{
  {
    "error",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Pb__PingResponse, error),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pb__ping_response__field_indices_by_name[] = {
  0,   /* field[0] = error */
};
static const ProtobufCIntRange pb__ping_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor pb__ping_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "pb.PingResponse",
  "PingResponse",
  "Pb__PingResponse",
  "pb",
  sizeof(Pb__PingResponse),
  1,
  pb__ping_response__field_descriptors,
  pb__ping_response__field_indices_by_name,
  1,  pb__ping_response__number_ranges,
  (ProtobufCMessageInit) pb__ping_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor pb__subscription_request__field_descriptors[10] =
{
  {
    "clientID",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Pb__SubscriptionRequest, clientid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "subject",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Pb__SubscriptionRequest, subject),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "qGroup",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Pb__SubscriptionRequest, qgroup),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "inbox",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Pb__SubscriptionRequest, inbox),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "maxInFlight",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Pb__SubscriptionRequest, maxinflight),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ackWaitInSecs",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Pb__SubscriptionRequest, ackwaitinsecs),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "durableName",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Pb__SubscriptionRequest, durablename),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "startPosition",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Pb__SubscriptionRequest, startposition),
    &pb__start_position__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "startSequence",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Pb__SubscriptionRequest, startsequence),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "startTimeDelta",
    12,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Pb__SubscriptionRequest, starttimedelta),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pb__subscription_request__field_indices_by_name[] = {
  5,   /* field[5] = ackWaitInSecs */
  0,   /* field[0] = clientID */
  6,   /* field[6] = durableName */
  3,   /* field[3] = inbox */
  4,   /* field[4] = maxInFlight */
  2,   /* field[2] = qGroup */
  7,   /* field[7] = startPosition */
  8,   /* field[8] = startSequence */
  9,   /* field[9] = startTimeDelta */
  1,   /* field[1] = subject */
};
static const ProtobufCIntRange pb__subscription_request__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 10, 7 },
  { 0, 10 }
};
const ProtobufCMessageDescriptor pb__subscription_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "pb.SubscriptionRequest",
  "SubscriptionRequest",
  "Pb__SubscriptionRequest",
  "pb",
  sizeof(Pb__SubscriptionRequest),
  10,
  pb__subscription_request__field_descriptors,
  pb__subscription_request__field_indices_by_name,
  2,  pb__subscription_request__number_ranges,
  (ProtobufCMessageInit) pb__subscription_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor pb__subscription_response__field_descriptors[2] =
{
  {
    "ackInbox",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Pb__SubscriptionResponse, ackinbox),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "error",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Pb__SubscriptionResponse, error),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pb__subscription_response__field_indices_by_name[] = {
  0,   /* field[0] = ackInbox */
  1,   /* field[1] = error */
};
static const ProtobufCIntRange pb__subscription_response__number_ranges[1 + 1] =
{
  { 2, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor pb__subscription_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "pb.SubscriptionResponse",
  "SubscriptionResponse",
  "Pb__SubscriptionResponse",
  "pb",
  sizeof(Pb__SubscriptionResponse),
  2,
  pb__subscription_response__field_descriptors,
  pb__subscription_response__field_indices_by_name,
  1,  pb__subscription_response__number_ranges,
  (ProtobufCMessageInit) pb__subscription_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor pb__unsubscribe_request__field_descriptors[4] =
{
  {
    "clientID",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Pb__UnsubscribeRequest, clientid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "subject",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Pb__UnsubscribeRequest, subject),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "inbox",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Pb__UnsubscribeRequest, inbox),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "durableName",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Pb__UnsubscribeRequest, durablename),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pb__unsubscribe_request__field_indices_by_name[] = {
  0,   /* field[0] = clientID */
  3,   /* field[3] = durableName */
  2,   /* field[2] = inbox */
  1,   /* field[1] = subject */
};
static const ProtobufCIntRange pb__unsubscribe_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor pb__unsubscribe_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "pb.UnsubscribeRequest",
  "UnsubscribeRequest",
  "Pb__UnsubscribeRequest",
  "pb",
  sizeof(Pb__UnsubscribeRequest),
  4,
  pb__unsubscribe_request__field_descriptors,
  pb__unsubscribe_request__field_indices_by_name,
  1,  pb__unsubscribe_request__number_ranges,
  (ProtobufCMessageInit) pb__unsubscribe_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor pb__close_request__field_descriptors[1] =
{
  {
    "clientID",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Pb__CloseRequest, clientid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pb__close_request__field_indices_by_name[] = {
  0,   /* field[0] = clientID */
};
static const ProtobufCIntRange pb__close_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor pb__close_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "pb.CloseRequest",
  "CloseRequest",
  "Pb__CloseRequest",
  "pb",
  sizeof(Pb__CloseRequest),
  1,
  pb__close_request__field_descriptors,
  pb__close_request__field_indices_by_name,
  1,  pb__close_request__number_ranges,
  (ProtobufCMessageInit) pb__close_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor pb__close_response__field_descriptors[1] =
{
  {
    "error",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Pb__CloseResponse, error),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pb__close_response__field_indices_by_name[] = {
  0,   /* field[0] = error */
};
static const ProtobufCIntRange pb__close_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor pb__close_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "pb.CloseResponse",
  "CloseResponse",
  "Pb__CloseResponse",
  "pb",
  sizeof(Pb__CloseResponse),
  1,
  pb__close_response__field_descriptors,
  pb__close_response__field_indices_by_name,
  1,  pb__close_response__number_ranges,
  (ProtobufCMessageInit) pb__close_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue pb__start_position__enum_values_by_number[5] =
{
  { "NewOnly", "PB__START_POSITION__NewOnly", 0 },
  { "LastReceived", "PB__START_POSITION__LastReceived", 1 },
  { "TimeDeltaStart", "PB__START_POSITION__TimeDeltaStart", 2 },
  { "SequenceStart", "PB__START_POSITION__SequenceStart", 3 },
  { "First", "PB__START_POSITION__First", 4 },
};
static const ProtobufCIntRange pb__start_position__value_ranges[] = {
{0, 0},{0, 5}
};
static const ProtobufCEnumValueIndex pb__start_position__enum_values_by_name[5] =
{
  { "First", 4 },
  { "LastReceived", 1 },
  { "NewOnly", 0 },
  { "SequenceStart", 3 },
  { "TimeDeltaStart", 2 },
};
const ProtobufCEnumDescriptor pb__start_position__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "pb.StartPosition",
  "StartPosition",
  "Pb__StartPosition",
  "pb",
  5,
  pb__start_position__enum_values_by_number,
  5,
  pb__start_position__enum_values_by_name,
  1,
  pb__start_position__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
