var annotated_dup =
[
    [ "jsAccountInfo", "structjs_account_info.html", "structjs_account_info" ],
    [ "jsAccountLimits", "structjs_account_limits.html", "structjs_account_limits" ],
    [ "jsAPIStats", "structjs_a_p_i_stats.html", "structjs_a_p_i_stats" ],
    [ "jsClusterInfo", "structjs_cluster_info.html", "structjs_cluster_info" ],
    [ "jsConsumerConfig", "structjs_consumer_config.html", "structjs_consumer_config" ],
    [ "jsConsumerInfo", "structjs_consumer_info.html", "structjs_consumer_info" ],
    [ "jsConsumerSequenceMismatch", "structjs_consumer_sequence_mismatch.html", "structjs_consumer_sequence_mismatch" ],
    [ "jsExternalStream", "structjs_external_stream.html", "structjs_external_stream" ],
    [ "jsLostStreamData", "structjs_lost_stream_data.html", "structjs_lost_stream_data" ],
    [ "jsMsgMetaData", "structjs_msg_meta_data.html", "structjs_msg_meta_data" ],
    [ "jsOptions", "structjs_options.html", "structjs_options" ],
    [ "jsPeerInfo", "structjs_peer_info.html", "structjs_peer_info" ],
    [ "jsPlacement", "structjs_placement.html", "structjs_placement" ],
    [ "jsPubAck", "structjs_pub_ack.html", "structjs_pub_ack" ],
    [ "jsPubAckErr", "structjs_pub_ack_err.html", "structjs_pub_ack_err" ],
    [ "jsPubOptions", "structjs_pub_options.html", "structjs_pub_options" ],
    [ "jsSequencePair", "structjs_sequence_pair.html", "structjs_sequence_pair" ],
    [ "jsStreamConfig", "structjs_stream_config.html", "structjs_stream_config" ],
    [ "jsStreamInfo", "structjs_stream_info.html", "structjs_stream_info" ],
    [ "jsStreamSource", "structjs_stream_source.html", "structjs_stream_source" ],
    [ "jsStreamSourceInfo", "structjs_stream_source_info.html", "structjs_stream_source_info" ],
    [ "jsStreamState", "structjs_stream_state.html", "structjs_stream_state" ],
    [ "jsSubOptions", "structjs_sub_options.html", "structjs_sub_options" ],
    [ "natsMsgList", "structnats_msg_list.html", "structnats_msg_list" ]
];