ignore:
  - "test/**"
  - "examples/**"
  - "src/win/**"
  - "src/unix/**"
  - "src/stan/protocol.pb-c.c"
coverage:
  precision: 2
  round: down
  range: "70...80"
  status:
    project:
      default:
        target: 65%
        threshold: 1%
github_checks:
  annotations: true
comment:
  require_changes: false